branches: "main"
pipeline:
    deploy:
        image: "registry.home.estelsmith.com/ci-ansible:latest"
        secrets:
            - "ansible_become_password"
            - "ansible_host"
            - "ansible_remote_user"
            - "deploy_key"
        commands:
            - echo -n "$${ANSIBLE_BECOME_PASSWORD}" > .ansible_password
            - echo -n "$${DEPLOY_KEY}" > deploy_key; chmod 0600 deploy_key
            - >
                ansible-playbook
                --private-key deploy_key
                --user "$${ANSIBLE_REMOTE_USER}"
                -i "$${ANSIBLE_HOST},"
                playbooks/deploy.yml
